### ISSUE TITLE
Broken provenance entries

### ISSUE THREAD

**Issue by andrew-torda** [ropensci/taxadb#96]
Is it possible that the provenance file is a bit broken ?
If I do,
```
  library(taxadb)
  a <- taxadb::get_ids (names=c("homo sapiens"))

```I get,
```
Error in switch(compression, gzip = gzfile(path, ...), bz2 = bzfile(path,  : 
  EXPR must be a length 1 vector
In addition: Warning message:
In FUN(X[[i]], ...) :
  No sources found for hash://sha256/ae98e3de1cadd69c064aa7aeb26b89251b49926207d41f8185af28d5f7a8853d

```
I think there are two broken entries,
   2019_dwc_ncbi
   2021_common_itis

Does this then lead to the switch error, that seems to come from dbpylr falling over ?

**Comment by cboettig** [comment]
(will try and get an update to contentid soon to make sure it's a bit broader searching. also, once those data register hash-archive, the old resolver should start to work.  apologies the new system clearly needs a bit of robustness testing! Thanks for your bug reports)

**Comment by andrew-torda** [comment]
The environment variable does fix it. Many thanks.
I was wondering if there should be a way for `taxa_tbl()` to return a code saying it is not happy. Returning an empty tibble does not work, but it was not clear to me what the best approach would be without making the code less readable.
